-- Adds the EMAIL column required by the schema contract.
USE SCHEMA CURATED;

ALTER TABLE ACCOUNTS ADD COLUMN IF NOT EXISTS EMAIL VARCHAR;

ALTER TABLE ACCOUNTS ADD CONSTRAINT UQ_ACCOUNTS_EMAIL UNIQUE (EMAIL);
