-- Demo pharma tables backing the OSI semantic view (AbbVie ontology use case).
-- Run once before importing abbvie_pharma_intelligence_v2.1.0.yaml

USE DATABASE ABBVIE_DATAOPS_DEV;
USE SCHEMA CURATED;

CREATE TABLE IF NOT EXISTS THERAPY_AREAS (
    THERAPY_AREA_ID   STRING PRIMARY KEY,
    THERAPY_AREA_NAME STRING,
    PARENT_AREA       STRING,
    DESCRIPTION       STRING,
    PRIORITY_LEVEL    STRING
);

CREATE TABLE IF NOT EXISTS PATIENTS (
    PATIENT_ID        STRING PRIMARY KEY,
    AGE               INTEGER,
    GENDER            STRING,
    PRIMARY_DIAGNOSIS STRING,
    DIAGNOSIS_CODE      STRING,
    THERAPY_AREA_ID   STRING,
    ENROLLMENT_DATE   DATE,
    INSURANCE_TYPE    STRING,
    REGION            STRING
);

CREATE TABLE IF NOT EXISTS DRUGS (
    DRUG_ID               STRING PRIMARY KEY,
    BRAND_NAME            STRING,
    GENERIC_NAME          STRING,
    THERAPY_AREA_ID       STRING,
    MECHANISM_OF_ACTION   STRING,
    ROUTE_OF_ADMINISTRATION STRING,
    APPROVAL_DATE         DATE,
    PATENT_EXPIRY         DATE,
    STATUS                STRING
);

CREATE TABLE IF NOT EXISTS FACILITIES (
    FACILITY_ID         STRING PRIMARY KEY,
    FACILITY_NAME       STRING,
    FACILITY_TYPE       STRING,
    HEALTH_SYSTEM       STRING,
    ADDRESS_STATE       STRING,
    REGION              STRING,
    BED_COUNT           INTEGER,
    IS_TEACHING_HOSPITAL BOOLEAN,
    INFUSION_CENTER     BOOLEAN
);

CREATE TABLE IF NOT EXISTS PRESCRIBERS (
    PRESCRIBER_ID   STRING PRIMARY KEY,
    FIRST_NAME      STRING,
    LAST_NAME       STRING,
    NPI             STRING,
    SPECIALTY       STRING,
    FACILITY_ID     STRING,
    THERAPY_AREA_ID STRING,
    YEARS_IN_PRACTICE INTEGER,
    IS_KOL          BOOLEAN
);

CREATE TABLE IF NOT EXISTS PRESCRIPTIONS (
    RX_ID               STRING PRIMARY KEY,
    PATIENT_ID          STRING,
    DRUG_ID             STRING,
    PRESCRIBER_ID       STRING,
    FACILITY_ID         STRING,
    FILL_DATE           DATE,
    DAYS_SUPPLY         INTEGER,
    REFILL_NUMBER       INTEGER,
    QUANTITY            FLOAT,
    PRIOR_AUTH_REQUIRED BOOLEAN,
    SWITCH_FROM_DRUG_ID STRING,
    SWITCH_REASON       STRING
);

CREATE TABLE IF NOT EXISTS TREATMENT_PATHWAYS (
    PATHWAY_ID      STRING PRIMARY KEY,
    THERAPY_AREA_ID STRING,
    DIAGNOSIS       STRING,
    LINE_OF_THERAPY INTEGER,
    DRUG_ID         STRING,
    PRIOR_DRUG_ID   STRING,
    SWITCH_CRITERIA STRING,
    EVIDENCE_LEVEL  STRING,
    GUIDELINE_SOURCE STRING
);

CREATE TABLE IF NOT EXISTS ADVERSE_EVENTS (
    AE_ID                 STRING PRIMARY KEY,
    PATIENT_ID            STRING,
    DRUG_ID               STRING,
    EVENT_TYPE            STRING,
    EVENT_TERM            STRING,
    SEVERITY              STRING,
    SERIOUS               BOOLEAN,
    ONSET_DATE            DATE,
    RESOLUTION_DATE       DATE,
    OUTCOME               STRING,
    REPORTER_TYPE         STRING,
    CAUSALITY_ASSESSMENT  STRING
);

-- Seed minimal demo data for semantic view queries
MERGE INTO THERAPY_AREAS t USING (
  SELECT * FROM VALUES
    ('TA_RHEUM', 'Rheumatology', 'TA_IMMUNO', 'Autoimmune joint disease', 'Primary'),
    ('TA_IMMUNO', 'Immunology', NULL, 'Immunology parent', 'Primary')
) v(THERAPY_AREA_ID, THERAPY_AREA_NAME, PARENT_AREA, DESCRIPTION, PRIORITY_LEVEL)
ON t.THERAPY_AREA_ID = v.THERAPY_AREA_ID
WHEN NOT MATCHED THEN INSERT VALUES (v.THERAPY_AREA_ID, v.THERAPY_AREA_NAME, v.PARENT_AREA, v.DESCRIPTION, v.PRIORITY_LEVEL);

MERGE INTO DRUGS t USING (
  SELECT * FROM VALUES
    ('DRUG_HUMIRA', 'HUMIRA', 'adalimumab', 'TA_RHEUM', 'TNF inhibitor', 'Subcutaneous', DATE '2002-12-31', DATE '2023-01-01', 'Mature'),
    ('DRUG_RINVOQ', 'RINVOQ', 'upadacitinib', 'TA_RHEUM', 'JAK inhibitor', 'Oral', DATE '2019-08-16', DATE '2030-01-01', 'Growth')
) v(DRUG_ID, BRAND_NAME, GENERIC_NAME, THERAPY_AREA_ID, MECHANISM_OF_ACTION, ROUTE_OF_ADMINISTRATION, APPROVAL_DATE, PATENT_EXPIRY, STATUS)
ON t.DRUG_ID = v.DRUG_ID
WHEN NOT MATCHED THEN INSERT VALUES (v.DRUG_ID, v.BRAND_NAME, v.GENERIC_NAME, v.THERAPY_AREA_ID, v.MECHANISM_OF_ACTION, v.ROUTE_OF_ADMINISTRATION, v.APPROVAL_DATE, v.PATENT_EXPIRY, v.STATUS);

MERGE INTO PATIENTS t USING (
  SELECT * FROM VALUES
    ('PAT001', 52, 'Female', 'Rheumatoid Arthritis', 'M06.9', 'TA_RHEUM', DATE '2024-01-15', 'Commercial', 'Midwest'),
    ('PAT002', 61, 'Male', 'Rheumatoid Arthritis', 'M05.79', 'TA_RHEUM', DATE '2023-06-01', 'Medicare', 'Northeast'),
    ('PAT003', 45, 'Female', 'Psoriatic Arthritis', 'L40.50', 'TA_RHEUM', DATE '2024-03-20', 'Commercial', 'West')
) v(PATIENT_ID, AGE, GENDER, PRIMARY_DIAGNOSIS, DIAGNOSIS_CODE, THERAPY_AREA_ID, ENROLLMENT_DATE, INSURANCE_TYPE, REGION)
ON t.PATIENT_ID = v.PATIENT_ID
WHEN NOT MATCHED THEN INSERT VALUES (v.PATIENT_ID, v.AGE, v.GENDER, v.PRIMARY_DIAGNOSIS, v.DIAGNOSIS_CODE, v.THERAPY_AREA_ID, v.ENROLLMENT_DATE, v.INSURANCE_TYPE, v.REGION);

MERGE INTO FACILITIES t USING (
  SELECT * FROM VALUES
    ('FAC001', 'Northwestern Memorial', 'Academic Medical Center', 'NM Health', 'IL', 'Midwest', 894, TRUE, TRUE),
    ('FAC002', 'Mayo Clinic Rochester', 'Academic Medical Center', 'Mayo', 'MN', 'Midwest', 1265, TRUE, TRUE)
) v(FACILITY_ID, FACILITY_NAME, FACILITY_TYPE, HEALTH_SYSTEM, ADDRESS_STATE, REGION, BED_COUNT, IS_TEACHING_HOSPITAL, INFUSION_CENTER)
ON t.FACILITY_ID = v.FACILITY_ID
WHEN NOT MATCHED THEN INSERT VALUES (v.FACILITY_ID, v.FACILITY_NAME, v.FACILITY_TYPE, v.HEALTH_SYSTEM, v.ADDRESS_STATE, v.REGION, v.BED_COUNT, v.IS_TEACHING_HOSPITAL, v.INFUSION_CENTER);

MERGE INTO PRESCRIBERS t USING (
  SELECT * FROM VALUES
    ('HCP001', 'Sarah', 'Chen', '1234567890', 'Rheumatology', 'FAC001', 'TA_RHEUM', 18, TRUE),
    ('HCP002', 'Michael', 'Patel', '0987654321', 'Rheumatology', 'FAC002', 'TA_RHEUM', 22, FALSE)
) v(PRESCRIBER_ID, FIRST_NAME, LAST_NAME, NPI, SPECIALTY, FACILITY_ID, THERAPY_AREA_ID, YEARS_IN_PRACTICE, IS_KOL)
ON t.PRESCRIBER_ID = v.PRESCRIBER_ID
WHEN NOT MATCHED THEN INSERT VALUES (v.PRESCRIBER_ID, v.FIRST_NAME, v.LAST_NAME, v.NPI, v.SPECIALTY, v.FACILITY_ID, v.THERAPY_AREA_ID, v.YEARS_IN_PRACTICE, v.IS_KOL);

MERGE INTO PRESCRIPTIONS t USING (
  SELECT * FROM VALUES
    ('RX001', 'PAT001', 'DRUG_HUMIRA', 'HCP001', 'FAC001', DATE '2025-01-10', 30, 0, 2.0, FALSE, NULL, NULL),
    ('RX002', 'PAT001', 'DRUG_RINVOQ', 'HCP001', 'FAC001', DATE '2025-04-15', 30, 0, 30.0, TRUE, 'DRUG_HUMIRA', 'Inadequate response'),
    ('RX003', 'PAT002', 'DRUG_HUMIRA', 'HCP002', 'FAC002', DATE '2025-02-01', 90, 1, 2.0, FALSE, NULL, NULL),
    ('RX004', 'PAT003', 'DRUG_RINVOQ', 'HCP001', 'FAC001', DATE '2025-05-01', 30, 0, 30.0, FALSE, NULL, NULL)
) v(RX_ID, PATIENT_ID, DRUG_ID, PRESCRIBER_ID, FACILITY_ID, FILL_DATE, DAYS_SUPPLY, REFILL_NUMBER, QUANTITY, PRIOR_AUTH_REQUIRED, SWITCH_FROM_DRUG_ID, SWITCH_REASON)
ON t.RX_ID = v.RX_ID
WHEN NOT MATCHED THEN INSERT VALUES (v.RX_ID, v.PATIENT_ID, v.DRUG_ID, v.PRESCRIBER_ID, v.FACILITY_ID, v.FILL_DATE, v.DAYS_SUPPLY, v.REFILL_NUMBER, v.QUANTITY, v.PRIOR_AUTH_REQUIRED, v.SWITCH_FROM_DRUG_ID, v.SWITCH_REASON);

MERGE INTO ADVERSE_EVENTS t USING (
  SELECT * FROM VALUES
    ('AE001', 'PAT001', 'DRUG_HUMIRA', 'Infection', 'Upper respiratory infection', 'Mild', FALSE, DATE '2025-02-01', DATE '2025-02-14', 'Recovered', 'Physician', 'Possible')
) v(AE_ID, PATIENT_ID, DRUG_ID, EVENT_TYPE, EVENT_TERM, SEVERITY, SERIOUS, ONSET_DATE, RESOLUTION_DATE, OUTCOME, REPORTER_TYPE, CAUSALITY_ASSESSMENT)
ON t.AE_ID = v.AE_ID
WHEN NOT MATCHED THEN INSERT VALUES (v.AE_ID, v.PATIENT_ID, v.DRUG_ID, v.EVENT_TYPE, v.EVENT_TERM, v.SEVERITY, v.SERIOUS, v.ONSET_DATE, v.RESOLUTION_DATE, v.OUTCOME, v.REPORTER_TYPE, v.CAUSALITY_ASSESSMENT);
