status = warn
appender.console.type = Console
appender.console.name = console
appender.console.target = SYSTEM_ERR
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} %p [%t] %c %x - %m%n

logger.openlineage.name = io.openlineage
logger.openlineage.level = INFO
logger.iceberg.name = org.apache.iceberg
logger.iceberg.level = INFO

rootLogger.level = WARN
rootLogger.appenderRef.stdout.ref = console
